### ISSUE TITLE
Incorrect command in demo

### ISSUE THREAD

**Issue by brk3** [Azure/caf-terraform-landingzones-accelerator#3]
When using command provided in https://github.com/Azure/caf-terraform-landingzones-starter/blob/starter/configuration/demo/README.md for deploying the launchpad (1. Launchpad-level0 landing zones -> Deploy the launchpad), I get the following:

```
$ export environment=demo
$ rover -lz /tf/caf/public/landingzones/caf_launchpad \
  -var-folder /tf/caf/configuration/${environment}/level0 \
  -parallelism 30 \
  -level level0 \
  -env ${environment} \
  -launchpad \
  -a plan
...
var.dynamic_keyvault_secrets
  Enter a value:
```

In order to make it correctly I changed the value of `-var-folder` in the above to `/tf/caf/configuration/${environment}/level0/launchpad` so it could correctly find the vars.

Seems like an easy fix but I'm new to rover and the structure of this project so opted to submit this issue instead for anyone else that may come across this.

**Comment by arnaudlh** [comment]
thanks @brk3 - will fix - don't hesitate to submit a PR :)
