### ISSUE TITLE
Error: Unsupported block type; Blocks of type "contact" are not expected here.

### ISSUE THREAD

**Issue by EntityAdam** [Azure/caf-terraform-landingzones-accelerator#6]
**Describe the bug**

```
Terraform plan return code: 0
Terraform returned errors:

Error: Unsupported block type

  on /home/vscode/.terraform.cache/modules/launchpad/modules/security/keyvault/keyvault.tf line 50, in resource "azurerm_key_vault" "keyvault":
  50:   dynamic "contact" {

Blocks of type "contact" are not expected here.

Error on or near line 446: Error running terraform plan; exiting with status 2000
```

**To Reproduce**

1. `git clone https://github.com/Azure/caf-terraform-landingzones-starter.git`
2. Reopen in container
3. `git clone --branch 2010.0.0 https://github.com/Azure/caf-terraform-landingzones.git /tf/caf/public`
4. `rover login`
5. `rover -lz /tf/caf/public/landingzones/caf_launchpad -launchpad -var-folder /tf/caf/configuration/demo/level0/launchpad -a apply`
6. See error

**Expected behavior**
Expecting the launchpad to deploy.

**Screenshots**

**Environment (please complete the following information):**

- OS: Windows 10 with WSL2 Ubuntu 20.04
- Rover Version: aztfmod/rover:2010.2808

**Additional context**
Following along with the getting started video here: https://www.youtube.com/watch?v=M5BXm30IpdY

**Comment by EntityAdam** [comment]
I was able to spend a few cycles on this.

In `/tf/caf/public/caf_launchpad/main.tf` I changed the `hashicorp/azurerm` version from 2.33.0 to version 2.37.0.

Once I updated the version, this worked as expected, so instead of pulling from the tag mentioned in the docs, I pulled from master.

**Comment by arnaudlh** [comment]
thanks for the PR @EntityAdam
