### ISSUE TITLE
Error: Failed to install provider || for multiple providers. 

### ISSUE THREAD

**Issue by narendermann** [Azure/caf-terraform-landingzones-accelerator#66]
Initializing provider plugins...
- Finding hashicorp/random versions matching "~> 2.2.1"...
- Finding hashicorp/external versions matching "~> 1.2.0"...
- Finding hashicorp/null versions matching "~> 2.1.0"...
- Finding hashicorp/tls versions matching "~> 2.2.0"...
- Finding aztfmod/azurecaf versions matching "~> 1.2.0"...
- Finding latest version of hashicorp/time...
- Finding hashicorp/azurerm versions matching "~> 2.55.0"...
- Finding hashicorp/azuread versions matching "~> 1.4.0"...
- Finding latest version of hashicorp/template...
╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/azuread v1.4.0: could not query provider registry for registry.terraform.io/hashicorp/azuread: failed to retrieve
│ authentication checksums for provider: the request failed after 2 attempts, please try again later: Get
│ "https://releases.hashicorp.com/terraform-provider-azuread/1.4.0/terraform-provider-azuread_1.4.0_SHA256SUMS": x509: certificate signed by unknown
│ authority
╵

╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/template v2.2.0: could not query provider registry for registry.terraform.io/hashicorp/template: failed to retrieve
│ authentication checksums for provider: the request failed after 2 attempts, please try again later: Get
│ "https://releases.hashicorp.com/terraform-provider-template/2.2.0/terraform-provider-template_2.2.0_SHA256SUMS": x509: certificate signed by unknown
│ authority
╵

╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/random v2.2.1: could not query provider registry for registry.terraform.io/hashicorp/random: failed to retrieve
│ authentication checksums for provider: the request failed after 2 attempts, please try again later: Get
│ "https://releases.hashicorp.com/terraform-provider-random/2.2.1/terraform-provider-random_2.2.1_SHA256SUMS": x509: certificate signed by unknown
│ authority
╵

╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/external v1.2.0: could not query provider registry for registry.terraform.io/hashicorp/external: failed to retrieve
│ authentication checksums for provider: the request failed after 2 attempts, please try again later: Get
│ "https://releases.hashicorp.com/terraform-provider-external/1.2.0/terraform-provider-external_1.2.0_SHA256SUMS": x509: certificate signed by unknown
│ authority
╵

╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/null v2.1.2: could not query provider registry for registry.terraform.io/hashicorp/null: failed to retrieve
│ authentication checksums for provider: the request failed after 2 attempts, please try again later: Get
│ "https://releases.hashicorp.com/terraform-provider-null/2.1.2/terraform-provider-null_2.1.2_SHA256SUMS": x509: certificate signed by unknown
│ authority
╵

╷
│ Error: Failed to install provider
│ 
│ Error while installing aztfmod/azurecaf v1.2.3: could not query provider registry for registry.terraform.io/aztfmod/azurecaf: failed to retrieve
│ authentication checksums for provider: the request failed after 2 attempts, please try again later: Get
│ "https://github.com/aztfmod/terraform-provider-azurecaf/releases/download/v1.2.3/terraform-provider-azurecaf_1.2.3_SHA256SUMS": x509: certificate
│ signed by unknown authority
╵

╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/azurerm v2.55.0: could not query provider registry for registry.terraform.io/hashicorp/azurerm: failed to retrieve
│ authentication checksums for provider: the request failed after 2 attempts, please try again later: Get
│ "https://releases.hashicorp.com/terraform-provider-azurerm/2.55.0/terraform-provider-azurerm_2.55.0_SHA256SUMS": x509: certificate signed by unknown
│ authority
╵

╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/tls v2.2.0: could not query provider registry for registry.terraform.io/hashicorp/tls: failed to retrieve
│ authentication checksums for provider: the request failed after 2 attempts, please try again later: Get
│ "https://releases.hashicorp.com/terraform-provider-tls/2.2.0/terraform-provider-tls_2.2.0_SHA256SUMS": x509: certificate signed by unknown authority
╵

╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/time v0.7.1: could not query provider registry for registry.terraform.io/hashicorp/time: failed to retrieve
│ authentication checksums for provider: the request failed after 2 attempts, please try again later: Get
│ "https://releases.hashicorp.com/terraform-provider-time/0.7.1/terraform-provider-time_0.7.1_SHA256SUMS": x509: certificate signed by unknown
│ authority
╵

Error on or near line 23; exiting with status 1

@calling clean_up_variables
cleanup variables
clean_up backend_files

**Comment by arnaudlh** [comment]
Closing as temp problem reaching out to the registry.
