### ISSUE TITLE
Broken link in README-piplines.md

### ISSUE THREAD

**Issue by heintonny** [Azure/caf-terraform-landingzones-accelerator#93]
A link in the file README-piplines.md is broken (404).
https://github.com/Azure/caf-terraform-landingzones-starter/blob/starter/configuration/sandpit/pipelines/README-pipelines.md

Customize your Azure DevOps environment as discussed [here](https://github.com/Azure/caf-terraform-landingzones/tree/master/landingzones/caf_launchpad/add-ons/azure_devops).

**Comment by arnaudlh** [comment]
Closing as fixed. Thanks for the feedback!
